### ISSUE TITLE
Building on ARM

### ISSUE THREAD

**Issue by toshipiazza** [falconre/falcon_capstone#1]
This should probably be marked as an issue upstream as well, in Mm7's repo. Building on ARM doesn't work because (I believe) `std::ios::raw::c_char` is marked as an `i8` on x86 and as `u8` on ARM. The following patch builds on ARM, but obviously doesn't build on x86:

```diff
diff --git a/src/capstone.rs b/src/capstone.rs
index 3ca1f0e..7e3f767 100644
--- a/src/capstone.rs
+++ b/src/capstone.rs
@@ -486,7 +486,7 @@ impl Capstone {
     pub fn reg_name(&self, reg_id: u32) -> Option<&str> {
         let name = unsafe {
             let name = cs_reg_name(self.handle.get(), reg_id);
-            if name == 0 as *const i8 {
+            if name == 0 as *const u8 {
                 return None;
             }
             CStr::from_ptr(name)
@@ -514,7 +514,7 @@ impl Capstone {
     pub fn group_name(&self, group_id: u32) -> Option<&str> {
         let name = unsafe {
             let name = cs_group_name(self.handle.get(), group_id);
-            if name == 0 as *const i8 {
+            if name == 0 as *const u8 {
                 return None;
             }
             CStr::from_ptr(name)
```

Probably just needs some `#[cfg]` magic to mediate between the two.

**Comment by endeav0r** [comment]
You may be able to move the `as`, so
``` if name as *const u8 == 0 ```
instead of 
``` if name == 0 as *const u8 ```

If that works, no `#[cfg]` magic necessary.

**Comment by toshipiazza** [comment]
Actually, would just doing `name.is_null()` work? I'm unsure if that has the same semantics as casting to an `i8` pointer and checking for 0. It builds on both ARM and x86 for me though.

**Comment by endeav0r** [comment]
I believe it would. If you want to do the PR, go ahead. Otherwise, I'll make the change in the next couple days.
