### ISSUE TITLE
Tests and examples don't build

### ISSUE THREAD

**Issue by wuggen** [falconre/falcon_capstone#4]
The tests and examples are unchanged since the crate was forked from Mm7's repository, and consequently don't build. The biggest problems are that they still import the crate as `capstone_rust` rather than `falcon_capstone`, and use `cs_mode` as a Rust enum (e.g. `cs::cs_mode::CS_MODE_64`) rather than the integer constants it now exists as (e.g. `cs::CS_MODE_64`).

EDIT: Additionally, any bindgen types that include a union don't implement Debug, so the build fails when attempting to use them in an assertion. Bindgen currently fails to correctly implement Debug for any struct that uses a Rust keyword as a field name, (`type` is the big offender here,) so this will unfortunately need some manual intervention.

**Comment by endeav0r** [comment]
Weird, I made a comment that said thanks for the PR, but it didn't come through. Thanks for the PR.
